### PR TITLE
Scan Media in the background

### PR DESCRIPTION
**Pull request by reaganlo**
Fixes Issue: #391

In order to avoid delay in loading the installer, scan the media in the
background as a separate go routine.

### CODE REVIEW

**Comment by mdhorn** [comment]
@reaganlo I still see the long delay from Language selection until the main screen loads on my dev-box.

**Comment by reaganlo** [comment]
@mhorn Made the change to get the results of scanning while loading the Disk Config page and not during its creation.

**Comment by mdhorn** [comment]
@reaganlo I can still launch, select language, select installation media, and the chooser list will appear with no content. If I use the "Rescan" it will get properly updated.  Still a race in there somewhere.

**Comment by reaganlo** [comment]
@mdhorn Ok..I haven't encountered it..yet. Looking into it.

**Pull request merged**
