### PR TITLE
Disable the root account if Admin set

### PR DESCRIPTION
**Pull request by mdhorn**
Fixes Issue: #212 

Changes proposed in this pull request:
- Lock root account is any user account has sudo/admin enabled

### CODE REVIEW

**Comment by mdhorn** [comment]
@pdxjohnny FYI

**Comment by pdxjohnny** [comment]
Sweet. Ideally we would have a test to verify this.

**Comment by mdhorn** [comment]
@reaganlo Updated due to new requirements; please review again.
@pdxjohnny This should be the final version I plan to merge.

**Comment by pdxjohnny** [comment]
This has gone a little beyond my understanding of this code base, but looks good so far as I can tell. I'm still working on that test case, got sidetracked today.

**Comment by mvincerx** [comment]
FYI: https://github.com/clearlinux/clear-linux-documentation/pull/401

**Pull request merged**
