### PR TITLE
kernel: Drop extra LTS kernels

### PR DESCRIPTION
**Pull request by mdhorn**
Changes proposed in this pull request:
- Only offer the latest LTS kernel as an alternative

### CODE REVIEW

**Comment by bryteise** [comment]
LGTM

**Comment by karthikprabhuvinod** [comment]
Changewise looks good to me but any reason why are we doing this? Why not allow more lts versions? I am guessing this is only during installation but the user can choose to change the kernel if he likes after installlation correct?

**Comment by mdhorn** [comment]
> Changewise looks good to me but any reason why are we doing this? Why not allow more lts versions? I am guessing this is only during installation but the user can choose to change the kernel if he likes after installlation correct?

Yes, they can change after the installation.
See https://github.com/clearlinux/distribution/issues/1857 for context.

**Comment by mdhorn** [comment]
Released in [2.4.3](https://github.com/clearlinux/clr-installer/releases/tag/2.4.3) in Clear Linux OS 32750 or higher.

**Pull request merged**
