### PR TITLE
Post image hooks

### PR DESCRIPTION
**Pull request by mdhorn**
Fixes Issue: #531

Changes proposed in this pull request:
- Add post-image YAML hook
- Make hooks indeterminate progress
- ensure we read the partition table when mounting loopback images

### CODE REVIEW

**Comment by mdhorn** [comment]
@gtkramer Please take a look at this when you get a moment.

**Comment by karthikprabhuvinod** [comment]
@mdhorn should we add this something to the baseline.yaml to make sure that this always run as part of make check-image and fails if someone accidentally removes the code?

**Comment by mdhorn** [comment]
> Thinking of it now, with this defined, I see that we dont have a post-image defined, it assumes it to be empty. So dont really see a way of automating it in tests.
> 
I did update the baseline check target to use a post-image hook to compress the image and updated the check in the make target.

> Maybe also good to squash the commits. Upto you.
> 
In this case, I wanted to keep the three commits. 
`storage: ensure we read the partition table` is sort of related, but something new we needed to as due to recent OS update.
`controller: Make hooks indeterminate` is a separate change I've been meaning to do for a while, but it became even more noticeable when we had a single, long-running post-image hook.


> apart from a rebase, LGTM otherwise.

**Comment by karthikprabhuvinod** [comment]
@mdhorn Nice LGTM :)

**Pull request merged**
