### PR TITLE
fall back to legacy bios when efi is not present

### PR DESCRIPTION
**Pull request by dorileo**
If the target system is not a efi system set the model to legacy bios mode.

Signed-off-by: Leandro Dorileo <leandro.maciel.dorileo@intel.com>

### CODE REVIEW

**Comment by karthikprabhuvinod** [comment]
I remember getting an error and getting stuck because of being on a legacy bios setting. Thanks for fixing this. I will test this soon.

**Comment by dorileo** [comment]
hy @karthikprabhuvinod  I suggest you waiting this [PR](https://github.com/clearlinux/clr-boot-manager/pull/213) to be merged and land on clr before testing.

**Comment by mdhorn** [comment]
@dorileo I'm wondering if it is a better idea to remove EFI check from the system check if it is really no longer a requirement -- like we did for AES.
And instead, when running interactive, we check for EFI, if not present log a warning and enable Legacy Mode.
Thoughts?

If EFI is no longer a hard requirement, we also need to update the compatibility page and checking script:
https://docs.01.org/clearlinux/latest/get-started/compatibility-check.html#compatibility-check

**Comment by dorileo** [comment]
@mdhorn I believe it should work, if it doesn't work we make it work :)

**Comment by mdhorn** [comment]
@dorileo working on a PR with a slightly different approach.

**Comment by dorileo** [comment]
That means we cant close this one. Thank you @mdhorn

**Pull request closed without merging**
