### PR TITLE
Remove UEFI requirement

### PR DESCRIPTION
**Pull request by mdhorn**
Fixes Issue: #517

Changes proposed in this pull request:
- Remove the requirement for UEFI booted system (Replaces #655)

### CODE REVIEW

**Comment by mdhorn** [comment]
This is blocked pending the addition of 'gptfdisk-bin' to the bootloader bundle to ensure that sgdisk is available to clr-boot-manager. @dorileo

**Comment by dorileo** [comment]
@mdhorn just send a patch adding the pkg to the bundle

**Comment by dorileo** [comment]
The PR LGTM. +1

**Comment by mdhorn** [comment]
> The PR LGTM. +1

I'm about to file a bug against the clr-boot-manager as it does not seem to update to a new kernel when using Legacy mode. I'll a link to the Github Issue once it is filed.

**Comment by mdhorn** [comment]
> > The PR LGTM. +1
> 
> I'm about to file a bug against the clr-boot-manager as it does not seem to update to a new kernel when using Legacy mode. I'll a link to the Github Issue once it is filed.

Setting a new kernel in CBM causes boot failure:
https://github.com/clearlinux/clr-boot-manager/issues/217

**Comment by mdhorn** [comment]
Blocked on the release of [clr-boot-manager 3.2.7](https://github.com/clearlinux/clr-boot-manager/releases/tag/v3.2.7)

**Comment by mdhorn** [comment]
UEFI requirement removed and available in clr-installer 2.4.1 starting with Clear Linux OS release 32510 or higher.

**Pull request merged**
