### PR TITLE
controller: Fix hang bug for cbm fails

### PR DESCRIPTION
**Pull request by mdhorn**
Changes proposed in this pull request:
- Fix installer hang when clr-boot-manager fails

### CODE REVIEW

**Comment by karthikprabhuvinod** [comment]
But if CBM fails, dont we need to report a failure too?

**Comment by mdhorn** [comment]
> But if CBM fails, dont we need to report a failure too?

We do, if you follow the return we log and fail there.

**Comment by mdhorn** [comment]
> > But if CBM fails, dont we need to report a failure too?
> 
> We do, if you follow the return we log and fail there.

Or the failure and output from the cbm is logged with
`cmd.RunAndLogWithEnv
`

**Comment by karthikprabhuvinod** [comment]
> > > But if CBM fails, dont we need to report a failure too?
> > 
> > 
> > We do, if you follow the return we log and fail there.
> 
> Or the failure and output from the cbm is logged with
> `cmd.RunAndLogWithEnv `

Okay, but thats in the log file, Do we see a fail on the progress?

**Comment by mdhorn** [comment]
> > > > But if CBM fails, dont we need to report a failure too?
> > > 
> > > 
> > > We do, if you follow the return we log and fail there.
> > 
> > 
> > Or the failure and output from the cbm is logged with
> > `cmd.RunAndLogWithEnv `
> 
> Okay, but thats in the log file, Do we see a fail on the progress?

Yes
https://github.com/clearlinux/clr-installer/blob/master/controller/controller.go#L409

**Pull request merged**
