### PR TITLE
isoutils: Reorder loadable modules

### PR DESCRIPTION
**Pull request by mdhorn**
Changes proposed in this pull request:
- Update the order of loading kernel modules for 5.8 changes

### CODE REVIEW

**Comment by karthikprabhu17** [comment]
Hi Mark, I checked the mail, do we know why loading the cdrom module before isofs fixes this issue?

**Comment by phmccarty** [comment]
+1

**Comment by mdhorn** [comment]
> Hi Mark, I checked the mail, do we know why loading the cdrom module before isofs fixes this issue?

Yes, as of the 5.8 kernel the isofs now explicitly lists a dependency on cdrom.

**Review by karthikprabhu17 — APPROVED** [review]
LGTM

**Review by karthikprabhu17 — APPROVED** [review]
LGTM

**Pull request merged**
