### PR TITLE
YAML cleanup

### PR DESCRIPTION
**Pull request by mdhorn**
Changes proposed in this pull request:
- Clean up older YAML files which are duplicates for production
- Updated the developer YAMLs to have hooks for swupd testing

### CODE REVIEW

**Comment by karthikprabhuvinod** [comment]
even inside InstallerYAMLSyntax.md

**Comment by mdhorn** [comment]
> even inside InstallerYAMLSyntax.md

I'm not sure what you were referencing here.

**Comment by karthikprabhuvinod** [comment]
> > even inside InstallerYAMLSyntax.md
> 
> I'm not sure what you were referencing here.

There are places :

https://github.com/clearlinux/clr-installer/blob/master/scripts/InstallerYAMLSyntax.md#children
line 55 ..we still use installer there. Maybe replace that with bdevice?

**Comment by mdhorn** [comment]
> > > even inside InstallerYAMLSyntax.md
> > 
> > 
> > I'm not sure what you were referencing here.
> 
> There are places :
> 
> https://github.com/clearlinux/clr-installer/blob/master/scripts/InstallerYAMLSyntax.md#children
> line 55 ..we still use installer there. Maybe replace that with bdevice?

That is just an alias name, it could be called anything.

**Comment by mdhorn** [comment]
Fixed in clr-installer 2.6.1, Clear Linux OS 33300 or higher.

**Pull request merged**
