### PR TITLE
gui: Introduces localization

### PR DESCRIPTION
**Pull request by reaganlo**
- Modifies the screen flow to first launch the Welcome (Language) page
- Adds localization package "gotext"
- Enables localization for "en_US", "zh_CN" and "es_MX"
- Modifies the strings to use localized version

Signed-off-by: Reagan Lopez <reagan.lopez@intel.com>

### CODE REVIEW

**Comment by mdhorn** [comment]
This looks great! Good work

**Comment by mdhorn** [comment]
Can we move the "Change Language" button to be left justified to separate it from the "Install" button?  Looking at it, I might even want both the Language and Exit buttons pushed left and leave the Install by itself on the right?  UX might have input on this too. If it is easy, please update. If it will take a while we can wait for other's input after the first beta release.

**Comment by mdhorn** [comment]
There are two Travis failures to be addressed:
1. One of the check is failing.
2. The installation of locales needs to be update in the Makefile :

```
diff --git a/Makefile b/Makefile
index 491faab0c5cb..8f2b614daf85 100644
--- a/Makefile
+++ b/Makefile
@@ -86,7 +86,8 @@ install: install-tui install-gui

 install-common:
        @install -D -m 644  $(top_srcdir)/themes/clr-installer.theme $(THEME_DIR)/clr-installer.theme
-       @install -D -m 644  $(top_srcdir)/locale/ $(LOCALE_DIR)/
+       @mkdir -p -m 755 $(LOCALE_DIR)/
+       @cp -rp --no-preserve=ownership  $(top_srcdir)/locale/* $(LOCALE_DIR)/
        @install -D -m 644  $(top_srcdir)/etc/clr-installer.yaml $(CONFIG_DIR)/clr-installer.yaml
        @install -D -m 644  $(top_srcdir)/etc/bundles.json $(CONFIG_DIR)/bundles.json
        @install -D -m 644  $(top_srcdir)/etc/kernels.json $(CONFIG_DIR)/kernels.json
@@ -109,7 +110,7 @@ uninstall:
        @rm -f $(THEME_DIR)/clr-installer.theme
        @rm -f $(THEME_DIR)/clr.png
        @rm -f $(THEME_DIR)/style.css
-       @rm -f $(LOCALE_DIR)/*/clr-installer.po
+       @rm -f $(LOCALE_DIR)/*/LC_MESSAGES/clr-installer.po
        @rm -f $(CONFIG_DIR)/clr-installer.yaml
        @rm -f $(CONFIG_DIR)/bundles.json
        @rm -f $(CONFIG_DIR)/kernels.json
```

**Comment by mdhorn** [comment]
@reaganlo I've also emailed a patch to show the languages in their own local language.

**Comment by reaganlo** [comment]
Thanks Mark for the review comments and patches. I have updated them. Also left aligned the "CHANGE LANGUAGE" button.

**Pull request merged**
