### PR TITLE
initrd_init_template: extend error message

### PR DESCRIPTION
**Pull request by stokito**
I mistakenly closed the #554 so here is a new one.

### CODE REVIEW

**Comment by jwakre** [comment]
@stokito The body message in the commit is too long for one line. The body message should be wrapped every ~72 characters: https://github.com/erlang/otp/wiki/writing-good-commit-messages

**Comment by mdhorn** [comment]
@stokito When you fix the commit message, you can just force push your full request instead of opening a new PR.

**Comment by mdhorn** [comment]
@stokito It would also be preferred that you please sign-off your commit:

>       -s, --signoff
>            Add Signed-off-by line by the committer at the end of the commit log message. The meaning of a signoff depends on the
>            project, but it typically certifies that committer has the rights to submit this work under the same license and
>            agrees to a Developer Certificate of Origin (see http://developercertificate.org/ for more information).
>

**Comment by mdhorn** [comment]
@stokito I'd be happy to merge this change if you can please first fix the commit to meet the standards. Wrap the commit lines at ~72, and if you can please add a sign-off.

**Comment by mdhorn** [comment]
Closing due to lack of update.

**Pull request closed without merging**
