### PR TITLE
vendor: update all of the packages

### PR DESCRIPTION
**Pull request by mdhorn**
Changes proposed in this pull request:
- Update to the latest version of each vendor package
  - Need a new gotk3 to fix a known bug

### CODE REVIEW

**Comment by jwakre** [comment]
@mdhorn What is the known bug?

**Comment by mdhorn** [comment]
> @mdhorn What is the known bug?

https://github.com/gotk3/gotk3/issues/361

**Comment by mdhorn** [comment]
> > @mdhorn What is the known bug?
> 
> [gotk3/gotk3#361](https://github.com/gotk3/gotk3/issues/361)

I have a fix for #614 which is not pushed yet as it hit the bug noted above.

**Comment by bryteise** [comment]
You may want to consider using https://dependabot.com/ at least for things that are versioned releases (oh if only all go things would version but I digress).

**Comment by mdhorn** [comment]
> You may want to consider using https://dependabot.com/ at least for things that are versioned releases (oh if only all go things would version but I digress).

Sadly, 6 of 17 vendor packages we use do not have releases, and one of them has not bumped their release in 8 months though they continue to fix bugs. :cry: 

We have vendor code check, status, and update commands built into the Makefile. We update the vendor once a month when we do a security check or when we find a bug that is fixed.

**Pull request merged**
