### PR TITLE
 Improve User account data entry

### PR DESCRIPTION
**Pull request by mdhorn**
Improve User account data entry

Fixes Issue: #28

### CODE REVIEW

**Comment by dorileo** [comment]
There's an inconsistency, I add a user, no validation message is shown, but when I add a second user the validation messages are displayed when entering the "new user" form screen.

**Comment by dorileo** [comment]
there's a padding space between user lines in the user list, is that intentional?

**Comment by dorileo** [comment]
when editing a user if I press the "reset" button the "user name" field is selected and nothing else? is it intentional? wouldn't be the case of disabling this button if editing a user?

**Comment by dorileo** [comment]
I have only these minor comments, otherwise LGTM.

**Comment by mdhorn** [comment]
> There's an inconsistency, I add a user, no validation message is shown, but when I add a second user the validation messages are displayed when entering the "new user" form screen.

This

**Comment by mdhorn** [comment]
> There's an inconsistency, I add a user, no validation message is shown, but when I add a second user the validation messages are displayed when entering the "new user" form screen.

This should be fixed now. Basically, the first time the code is run the default edit Title is an empty string and set it to empty string again did not trigger the OnChange code.

**Comment by mdhorn** [comment]
> there's a padding space between user lines in the user list, is that intentional?

This was intentional to keep with spacing on other screen and provide visual space between user accounts.

**Comment by mdhorn** [comment]
> when editing a user if I press the "reset" button the "user name" field is selected and nothing else? is it intentional? wouldn't be the case of disabling this button if editing a user?

The "reset" button was intended to put the User form back to the state when the screen was started. If adding a user, it would clear all the data; if modifying a user, it would restore the data to the starting state.

**Pull request merged**
